### ISSUE TITLE
Consider adding task runner

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#14]
### Thank You
@jpscaletti First of all thank you very much for putting up this awesome package.
I was looking for a simpler to use alternative to cookiecutter and believe I have found it in `Voodoo`.

### Add a TaskRunner
I believe there is a low hanging fruit to give `Voodoo` **superpowers**:
You may want to add a basic command execution capability to this already awesome package.
This would allow to endow a newly minted project to be supplemented with additional properties.
Such additional properties could for example be a `virtual environment` associated with the particular projects, the initiation of a `git repository` or fetching certain files from the internet.

#### Implementation:
Keep it simple.
User puts a `tasks.json` file into the template dir. That file contains an array of shell command.
Which are successively ran against python's `subprocess`. In its simplest form that file could look like:
```json
[
    "git init .",
    "pipenv shell"
]
```
*This means that in the newly created project folder a git repository and a python virtual environment will be created, once the main templating process has finished.*

#### Additional nodes
- exit codes should be checked and non-zero ones leading to termination of the command chain
- piping the `stdout` of a ran command into the `stdin` of its successor might also be added.
- This `Sublime Text` plugin essentially already implements all the code needed:
https://github.com/bit101/ProjectMaker/blob/b2e82189226cbf13383aedf6e4177307af35a50f/projectmaker.py#L296 (just adapt function to suit a non Sublime Text context)
- To be more clear:
```py
def exec_tasks(self):
    task_file = os.path.join(self.template_path, "tasks.json")
    if os.path.exists(task_file):
        with open(task_file, "r") as f:
            tasks = json.loads(f)
            for t in tasks:
                try:
                    subprocess.run(t, shell=True, check=True)
                except subprocess.CalledProcessError as e:
                    # handling non-zero exit codes
                    print(e) 
                    break
```

**Comment by jpscaletti** [comment]
Thank you very much for your kind words. 
After quite some time I'm working again on this project, and this feature will be next.

**Comment by pykong** [comment]
@jpscaletti Thank you for implementing. The task runner is still very welcome!

I am eager to try the new feature out in a couple of weeks from now (very busy). 
Keep up the awesome work!
