### ISSUE TITLE
Enhancement: Better support for template inheritance

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#15]
One of `Jinja2`'s prime features is the support of template inheritance.
http://jinja.pocoo.org/docs/2.10/templates/#template-inheritance

The problem I see with `Voodoo`'s implementation is that parent files will also get copied over to the project folder. 

Wouldn't it be better to reserve the `.tmpl` suffix only for those parent files?
Those could still be used as base templates, but will be omitted from copying over.
This inverts the selection process compared to the status quo.

Voodoo could then try to render all non-suffixed text files present under the template path.
Any non-text file (e.g. image files) would simply be copied. (Likely this could be achieved by catching exceptions that arise when trying to open/render non-text files. Hence not requiring an extensive list of file extensions for discerning.)

**Comment by jpscaletti** [comment]
The reason a `.tmpl` suffix is needed is for not processing some text files that could be misinterpreted as Jinja templates, like javascript files (a very common scenario).

I not sure what could be done to achieve this in a simple way

**Comment by pykong** [comment]
@jpscaletti 

Well, there is a simple way to unlock template inheritance (without copying the inherited template over):
_Put the template to be inherited from into a different directory._

All it takes would be to feed the additional path required to the FileSystemloader:
https://github.com/jpscaletti/copier/blob/cfbef80b31f2380976af7843549e46c3aa13d83f/copier/tools.py#L177

Simply changing it to:
```py
 _envops.setdefault("loader", jinja2.FileSystemLoader([src_path, extra_path]))
```

does the trick. Works like a charm on my system.

We would need to provide the extra path(s) as an additional command line argument though.
This leads straight to a question: Would you accept a PR of mine implementing the feature at hand?

**Comment by jpscaletti** [comment]
@pykong Sorry for the delay. I almost-kind-of-sure that if you list the parent files in the `_exclude` list, they still work but don't get copied... let me test it.

**Comment by pykong** [comment]
@jpscaletti Thanks for your reply. I am sure the most common use case for inheritance would be centralising content blocks to make your template folders more __DRY__.

For example I am using a single `.gitignore` parent file for all my python projects. This is great for __DRY__ reasons, e.g. not needing to maintain and update the same file in dozens of locations.

We can even customize the child files via blocks:
``` 
[% block custom_block %]
.do_it
[% endblock %]
```

This is very powerful stuff and such big upgrade to copier.

**Hence:** Merely excluding files is not enough. We need to allow specifying additional folders to source  parent files from in order to unlock the full power of template inheritance.

**Comment by jpscaletti** [comment]
Yes, sounds great. I would love to see your code.
