### ISSUE TITLE
Use some keys from copier.yml as default values for `exclude`, `include`, etc.

### ISSUE THREAD

**Issue by jpscaletti** [jpscaletti/copier#17]
The values should be the overwriteable by those passed as arguments to `copier.copy()`, because they are conveniences, not rules.

**Comment by pykong** [comment]
Can I use keys in `copier.yml` to specify the destination path?
It does not appear so:

```yml
dst_path: "."
```

Will result in: `"copier: error: the following arguments are required: dest"`, when omitting the destination path as the second command line argument.

I'd like to have my current working dir as the default destination path.
