### ISSUE TITLE
How to specify working dir of tasks

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#20]
I want to run all tasks in the freshly created dir.
Hence, is there a way to specify the working dir for the tasks to run in?

```yml
# Commands to be executed after the copy
_tasks:
    - cd [[ project_name ]]
    - git init
```
A simple cd command does not do the trick.
(Platform: Linux Mint)

**Comment by jpscaletti** [comment]
Hi, First of all, you don't need to change the working folder to the project because the tasks start in that folder.
However, every task runs independently and side-effects like changes to the current working folder, aren't preserved. You need to change the folder for each task like this:

```yaml
_tasks:
  - cd subfolder && a_command
  - cd subfolder && other_command
```

**Comment by pykong** [comment]
@jpscaletti Thanks!

**Comment by pykong** [comment]
It appears that tasks will be run in the destination dir starting with the `2.3.4` release.
https://github.com/jpscaletti/copier/blob/3edbaabe70a294b1bab838d13c04de297573ff4e/copier/main.py#L327

That would be great news!

@jpscaletti 
Can you confirm this?
If so we should add a tiny sentence to the `README.md` to inform about this.

**Comment by pykong** [comment]
I know understand where my problem with running tasks in the destination folder stems from.
I always want my copier-created project to reside in a new folder within the current directory.
I also want the name of that new folder to be identical to the project name.
Hence what I did in this regard was to layout a nested template structure like this:
```
.
├── copier.toml
└── [[ project_name ]]
    ├── app.py
```

I believe that putting the new project under a folder with the project's name represents a sensible default.

The problem with the current implementation is that in this regard you were required to specify the project name twice: Once via the `dst_path` argument and then via the prompt.

What could be a better way to handle this? How could we just give the project name once?

Possible solutions
Either:
1. Make prompt for `project name` optional: _Derive project name from the last segment of `dst_path`._

Or:
2. Make `dst_path` optional: _Always put the new project under a new folder name after project name in the current dir._

**Comment by pykong** [comment]
Constraining output to new folder versus allowing to paste newly generated files flat into the current folder would allow easier removal as well: #22

**Comment by pykong** [comment]
Well, it appears we can resort to using the `folder_name` variable which is being used internally.

Like so:

```
[[ folder_name ]]
```
