### ISSUE TITLE
Enhancement: Cleanup on failure

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#22]
To prevent defunct remnants of a failed attempt to create a project an already created folder should be deleted when the creation process fails (e.g. task runner experiences error).

**Comment by jpscaletti** [comment]
I consider this a feature.

But the removal of failed attempts can be achieved right now simply by wrapping the `copier.copy()` call in a try...except clause:

```python
import shutil

try:
    copier.copy(src, dst)
except:
    shutil.rmtree(dst, ignore_errors=True)
```

**Comment by pykong** [comment]
The consequence of not having a cleanup procedure is that, in case of failure to render the template, the user will get stranded with a defunct dir.

This is bad UX IMHO.
Would you consider merging #37 if I made the the cleanup process dependent on a command line flag? Just my suggestion ...

**Comment by jpscaletti** [comment]
🤔

**Comment by jpscaletti** [comment]
🤔

**Comment by jpscaletti** [comment]
ok, you are right

**Comment by pykong** [comment]
Great! You made the right choice! The ability to change one's mind is a tell tale sign of a good developer in my experience.
