### ISSUE TITLE
Enhancement: Improve output for tasks to be run

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#23]
Instead of one single line:

```bash
   _tasks? [['cd [[ project_name ]] && git init', 'cd [[ project_name ]]', 'pipenv install']] 
```
List commands and already substitute variables:

```bash
   Tasks to be run:
   - cd MyProject && git init
   - cd MyProject && pipenv install
```

As a bonus: Some progress indication while running those tasks would be very useful.
Like: 

```bash
Runnings task (2/5) --- Done
```

**Comment by jpscaletti** [comment]
I think that's a great idea. :)

**Comment by pykong** [comment]
@jpscaletti Are you already working on this feature?

**Comment by jpscaletti** [comment]
I think the first part "Instead of one single line: ..." was a bug caused by #36.

About the displaying of the tasks: no, I haven't done anything yet.

**Comment by pykong** [comment]
Could we maybe feature your https://github.com/jpscaletti/pyceo for a consistent look and feel?
(I imagine there is some `printf` function in there already. Haven't checked yet...)
