### ISSUE TITLE
Enhancement: Official integration of pipenv

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#24]
It is reasonable to assume that the one thing most users creating a new python project via `copier` may want to do is to initialize a virtual environment and install packages. 

Hence an official way to support `pipenv` would be very welcomed.

**Comment by jpscaletti** [comment]
You can do it now using tasks.. or you can do `python -m venv .venv && .venv/bin/pip install -e .` as a task...  You could also use `copier` to render a template of something that isn't a python project.

In other words, I think that would be too specialized when you can already do it by adding a line in the tasks settings of the `copier.yml` file.

So.. is not the direction I want to take this project.

**Comment by pykong** [comment]
I understand your point. Well, we can keep using the task runner for now.
