### ISSUE TITLE
Bug: Does not copy empty folders

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#25]
I have not been able to get empty folders getting copied to a generated project.
Once the folder is endowed with just a single file it is respected by the copying process.

This behavior I can reliably reproduce using the latest version of `copier` 2.1.0.

**Comment by jpscaletti** [comment]
That's a feature, was my first reaction! Because git does the same thing...

But git does the same thing as an artifact of its implementation ("there are no folders, just files with paths")... so you are right, is a bug... that I'm fixing right now.
