### ISSUE TITLE
Enhancement: Allow configuring template folder

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#26]
__How?__ Configuration via settings file and/or environment variable.
__Why?__ Simplifying command to: `copier init` _(Will then prompt for which template to be used to create the new project from a list of folders found in the template folder.)_

**Comment by jpscaletti** [comment]
SOund like a task for a toll built *on top* of copier I would prefer to keep it focused.

**Comment by pykong** [comment]
Sounds fair. I plan to use `copier` as the engine of a future Sublime Text in this regard.
