### ISSUE TITLE
Update Readme: Configuration file format

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#30]
@jpscaletti 

Three config file formats (`TOML`, `YAML` and `JSON`) find mention in the readme and the code base. As of the most recent version `copier.yaml` does not seem to work for me any longer, forcing me to switch to `json`.

Could you therefore maybe clarify which configuration file formats we can actually use?
Does the `README.md` require update in this regard?

**Comment by pykong** [comment]
Indeed `CHANGELOG.md` states that: 

> The recommended configuration file is now  copier.toml

https://github.com/jpscaletti/copier/blob/master/CHANGELOG.md#version-23-2019-04

Hence `README.md` need to reflect that change more explicitly.
The screenshot needs to be updated as well.

**Comment by jpscaletti** [comment]
After some reflection, I restored the `copier.yaml` or `copier.yml` as default configuration formats.
The TOML and JSON formats are also still supported and will continue to be so in the future.

**Comment by pykong** [comment]
Great. Personally, I find the array syntax of `yaml` cleaner than that of `json` or `toml`.
This is especially relevant to the tasks list.

**Comment by jpscaletti** [comment]
By the way, I uploaded the `2.4` version to PyPi today (Is now `2.4.1` because I forgot to exclude the yaml files by default).
