### ISSUE TITLE
Example: Passing function to data

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#33]
@jpscaletti 

The readme states that you can even pass a function as extra context via the `data` argument.

> Use the data argument to pass whatever extra context you want to be available in the templates. The arguments can be any valid Python value, even a function.

Can you provide an example of how to do so? I seem not to be able to make it work, nor have I found an example in the docs or tests.

Further, can we call such a function in our `Jinja2` templates then? _(That would be extremely useful!)_

**Comment by jpscaletti** [comment]
Yes, but the `data` argument is only available when calling the `copier.copy()` function, not from the command-line.

The values in `data` are passed to Jinja when rendering a template and can be any Python value, including a function. For example, if you do something like this:

```python
from datetime import datetime
import hashlib
import os
import copier


def get_random_key():
    return hashlib.sha1(os.urandom(32)).hexdigest()


data = {
    "get_random_key": get_random_key,
    "greeting": "Hello world!",
    "fruits": ["apple", "banana", "orange"],
    "now": datetime.utcnow
}

copier.copy(src, dst, data=data)
```

You can use those values in your templates like this:

```jinja2
{{ greeting }}

Current time is {{ now() }}.

A random key: "{{ get_random_key() }}".

We have this fruits: {{ ", ".join(fruits) }}.
```

**Comment by pykong** [comment]
Thanks for your in-depth answer! Indeed my confusion stemmed from me using `copier` solely from CLI so far. Obviously, we can not specify a python function in the `copier.yml`.

I may consider writing a thin wrapper for myself to download `gitognore` files.

```
[[ download_gitignore('python') ]]
```
