### ISSUE TITLE
Bug: Specifying _extra_paths in copier.yml does not work

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#38]
Neither specifying `_extra_paths` nor `_extra-paths` will result in those paths being respected.

Example:
```yml
_extra_paths:
- ~/Projects/.templates/.templates/
```

From debugging I found that the `extra_paths` variable never showes up in `config_data`:
https://github.com/jpscaletti/copier/blob/bfaefdb1e8d2fbf1270497af1641d52f710a7d52/copier/main.py#L183
copier version: `2.4.2`

**Comment by jpscaletti** [comment]
No,the problem was the conditional that allows the extra_paths, loaded from the config, to overwrite the value passed as an argument.
The code was:

```python
if extra_paths is None:
        extra_paths = user_extra_paths or []
```

but the empty value of `extra_paths` was an empty list, so it was never `True`  and the extra_paths from the config were always beign ignored.

**Comment by pykong** [comment]
The problem appeared that Jinja does not itself expand the `~`. It neither raises an error either.

```py
p = PosixPath('~/films/Monty Python')
p.expanduser()
PosixPath('/home/eric/films/Monty Python')
```
