### ISSUE TITLE
Enhancement: Add pyproject.toml

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#40]
`CONTRIBUTING.md` suggests `poetry` for development.
How then does it come that no `pyprojct.toml` is included?
Shouldn't we add one? Should we maybe replace `setup.py` entirely?

**Comment by jpscaletti** [comment]
Been there, done that.

Some things about poetry I didn't like last time I tried it:

- Even by using the install method with `curl`, poetry dependencies clashes with my own dependencies, at least in pyenv. It's probably a bug... I think poetry dependencies should be embedded into the library to avoid the problem completely... but its repo has tons of pending pull requests right now so I'm not very motivated to code it and send one more.

- Compared with `pip install .` is really slow (I know, pip doesn't generate a lock file automatically, but still it feels that takes forever).

(And before you ask, I *despise* pipenv and everything around it, so is also not an option for me)

So, thank you, but I want to wait a year for the packaging environment to stabilize a bit more.
I'm experimenting with using setup.cfg instead, like this guy: https://github.com/jaraco/skeleton

**Comment by pykong** [comment]
Thanks for your insight. Indeed I have not been able to make a dev setup working with `poetry` either.
It was the first time I actually used `poetry` -> thought it would live up to people considering it superior to `pipenv`. At least not for me.

`pipenv` works for my setup but then I am not developing packages on a regular basis.
(I heard its dependency resolution is really inept.)
