### ISSUE TITLE
Enhancement: Allow running pytest

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#41]
I'd like to run tests with pytest (vs mere tox).
Unfortunately, pytest complaints that it can not find the `copier` module.

Removing 
https://github.com/jpscaletti/copier/blob/bfaefdb1e8d2fbf1270497af1641d52f710a7d52/copier/__init__.py#L5

allows running tests by calling: 
```shell
> pytest
```

Maybe I am calling pytest the wrong way or this is indeed an issue.

**Comment by jpscaletti** [comment]
I have the package installed locally installed with `pip install -e .`  so I didn't noticed this was happening. Please pull again, I uploaded a fix and now you can run pytest as before with `pytest .`
