### ISSUE TITLE
Enhancement - Type annotate code base

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#42]
@jpscaletti What do you think of hardening `copier` with endowing all functions with type annotations?

Like the central copy function for example:

```py
def copy(
    src_path: str,
    dst_path: str,
    data: Optional[dict] = None,
    *,
    exclude: Optional[List[str]] = None,
    include: Optional[List[str]] = None,
    tasks: Optional[List[str]] = None,
    envops: Optional[dict] = None,
    extra_paths: Optional[List[str]] = None,
    pretend: bool = False,
    force: bool = False,
    skip: bool = False,
    quiet: bool = False
) -> None:
```

**Comment by jpscaletti** [comment]
Not a big fan because it makes the code uglier, I'm not very convinced of the benefits, and because I'm to lazy to add them... but I would be happy to merge something like this and discover what I was missing that make so many people excited about it.

**Comment by pykong** [comment]
Obviously, we won't be able to discuss pros and cons of type annotations in depth here.
(About the lazy thing: https://github.com/dropbox/pyannotate or Instagram/MonkeyType may do the grunt of the work for you in the future - required you got great test coverage. )

I despise the verbosity that it brings for many signatures.
In my work on `copier` there has been at least one instance where type annotations would have caught me calling a function with the wrong order of arguments earlier.

I am going to try bringing forth some extensive annotations and we can then decide whether it is something we wanna have in `copier`.

**Comment by pykong** [comment]
In my attempt to manually type annotate `copier` I made up my mind. 

At the current complexity, type annotations will not be of a big profit for `copier`.
From my personal experience, there is a break-even point between additional complexity and additional safety for using type hints. The small scale of the current `copier` code base does not yet justify their addition.

At a later point in time, we may resort to it though. Especially once either `pyannotate` or `MonkeyType` becommes usable. Closing this for now.

**Comment by jpscaletti** [comment]
I'm reopening this issue as I would like to try this idea.

**Comment by pykong** [comment]
This is surprising. But all the better.
Feel free to summon me in case you need any assistance.

**Comment by pykong** [comment]
@jpscaletti Have you made progress on this matter?

**Comment by pykong** [comment]
I am working on **PR** right, which fully type annotates the whole code base, excluding tests.
I am hoping to have it ready by next Sunday.
