### ISSUE TITLE
Minor Bug: Version in tests.helpers

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#46]
Shouldn't that be `2.4.2` by now? If so maybe dynamizing by sourcing the current version from a single source of truth would seem appropriate.

https://github.com/jpscaletti/copier/blob/302dde9b17a8198e08fe8c8cf034ed226112f752/tests/helpers.py#L17

**Comment by jpscaletti** [comment]
That is just test data, not the real version of the project.

**Comment by pykong** [comment]
Ah. OK! ;-)
