### ISSUE TITLE
Enhancement - Consider donation option

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#47]
With the most recent changes `copier` has become an incredibly valuable tool for myself and most certainly many other users.

I feel such a project deserves support.

If you like add a donation option, possibly even via adding a `FUNDING.yml` (allowing to tip directly via GitHub).

**Comment by jpscaletti** [comment]
It makes me happy that it's also valuable to you.

I don't delude myself thinking this has potential ever to gather any support beyond a coffee once-in-a-lifetime (see: https://staltz.com/software-below-the-poverty-line.html), but I'm also curious about GitHub's tips, so sure, why not!

**Comment by jpscaletti** [comment]
There is a waitlist... so let's wait

**Comment by pykong** [comment]
Good. Let's do that. :-)

**Comment by pykong** [comment]
Can we close this issue due to https://github.com/jpscaletti/copier/commit/d1318b4195fb1000c44dc36004bd8c9ac5e833c0?
