### ISSUE TITLE
Enhancement - Add requirements.txt

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#51]
Having a `requirements.txt` or possibly even a `requirements-dev.txt` would help when developing `copier`, by allowing easier installation of dependencies. This is of particular importance as we will not include modern package files such as `pyproject.toml` or `Pipfile` (See: #40).

- How come we do not have those files included?
- Am I doing something wrong here?

(_Side info_: I am using `pipenv` for development as I have not been able to get my dev setup running with `poetry`.)

**Comment by jpscaletti** [comment]
You don't need them. The "development" requirements are listed in `setup.cfg` at the `[options.extras_require] dev` section.

You can install them with pip by doing `pip install -e .[dev]`.

In OSX or Linux, you can run `make install` to do it for you.

That command will also install `copier` in development mode and its requirements si you don't need to run anything else. See the `Makefile` file for more pre-made commands you could use.

**Comment by pykong** [comment]
@jpscaletti Thanks, I didn't know about pip being able to parse "setup.cfg".
