### ISSUE TITLE
Bug - Root level __init__.py

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#56]
I have not been able to either user `pyannotate` or `MonkeyType` to add type hints to copier's code.

In the issue I opened on MonkeyType it was suggested this being due to the `__init__.py`
present at the root level of `copier`:
https://github.com/Instagram/MonkeyType/issues/139

Similar problems exist for `pyannotate`:
https://github.com/dropbox/pyannotate/issues/61

I do not possess the experience with developing python packages to judge whether the root level `__init__.py` should be there or not. However, it should be considered in light of the problems I have experienced.

**Comment by jpscaletti** [comment]
Frankly, I didn't know it could be a problem. Removing it will force you to install the package before running the tests (`pip install -e .` once is enough) but if it's preventing running those tools, I think it should be done.
