### ISSUE TITLE
Enhancement - Parent template folders

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#58]
I believe it would be very helpful to every user of `copier` to allow for **DRY**er templates. Common redundancies across templates which can not be addressed via the current functionality of `copier` are:
- sets of files (_e.g. all my web templates feature the same set of static files_)
- contents of `copier.yaml` (_e.g. I always run the same seven tasks, regardless of the project_)

#### Potential solutions:
- allow to inherit an entire folder: all folders of a given path will be copied over to the new rendered folder
- allow inheritance of `copier.yaml` files where a parent template can be included

### EDIT:
I believe this issue is not clear enough. In part because I wasn't sure what I was looking for.
I am working on making the idea clearer.

**Comment by jpscaletti** [comment]
I'm going to close the issue for now

**Comment by pykong** [comment]
@jpscaletti 
Yes, sure this should not go stale while I am still making up my mind. ;-)
