### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#59]
@jpscaletti 

Could you please give me a life sign whether you are still interested in developing `copier` any further? The issues and **PR**s are turning stale. I know very well that developing open source in your free time can be quite a time demanding but `copier` I believe fills a void for me and other users, being a simple more usable alternative to `cookiecutter`.

In case you do no longer want to actively maintain `copier` consider sharing push access, transferring ownership or encouraging friendly fork. In any case state the status of the project, so users can make an informed decision on using `copier` in accordance with good open-source practices.

**Comment by jpscaletti** [comment]
Yes, I'm still alive! Overwhelmed by a cold, work, and other things this keep piling up this month. I'm going to take a look at everything this weekend.

**Comment by pykong** [comment]
Great you are stil alive. Hope you are feeling better! :-)
OK. take your time then. No, stress.
Just wanted to know whether I should wait or fork.
I am here if you need me.
