### ISSUE TITLE
Suggestion - Submit to awesome list

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#60]
**TL:DR** `copier` is awesome! 
I see it offering the most functionality that [cookiecutter](https://github.com/cookiecutter/cookiecutter) possess without the bloat.  Hence we should consider submitting it to an awesome list to make it known to more users.

It could be one of those:
https://github.com/sindresorhus/awesome

Most likely the python list:
https://github.com/vinta/awesome-python

**Comment by jpscaletti** [comment]
Good idea!
Tell your friends, family, neighbors, and strangers! 😉 

https://github.com/vinta/awesome-python/pull/1350

**Comment by pykong** [comment]
Awesome. Great to see you back!

I like to merge two more PRs before we can release version 3:
- #61 
- And one I am preparing for #58

**Comment by pykong** [comment]
@jpscaletti 
We have reached 20 votes. Still, `copier` the underlying **PR** did not get merged.
Could you take care of that (before someone decides to unlike again and we fall below 20 again), as you are the author of the thread on the vinta repo?

https://github.com/vinta/awesome-python/pull/1350
