### ISSUE TITLE
Dealing with multiple config files.

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#65]
Having more than one config file in a source directory is an erroneous condition.
Maybe it is bikeshedding. Or maybe a corner case we may want to address.

Possible solutions:
1) Stick to the current precedence mechanism ignoring those files with lower precedence.
2) Resort to only supporting one file type (likely `yaml`).
3) Throw an error on encountering this situation.

@jpscaletti 
What do you think?

**Comment by pykong** [comment]
IMHO **2)** Is what to be preferred.

Only supporting `copier.yaml` (or less preferable `copier.toml`) would make code simpler, prevent the aforementioned condition. I am somewhat of an essentialist, hence  I believe that limiting options and placing constraints are actually a good thing.

My credo:
> Configurablity is the root of all evil.

**Comment by jpscaletti** [comment]
🤔 ok, let's go ahead and only support `copier.yaml`. It's also what I use anyway.

**Comment by pykong** [comment]
@jpscaletti 
Great! I am going to perform the required changes.
