### ISSUE TITLE
Enhancement - Sharing identical portions of copier.yaml

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#68]
My `copier.yaml` files do share a lot of content.
e.g. I have specified the same basic sequence of tasks to be run.

I would like to share some content between different `copier.yaml` files.

@jpscaletti
Do you get an idea of how we could achieve this?

_One idea:_
- We may somehow leverage Jinja2's inheritance mechanism like we already do for other templates.

Relates to: #58

**Comment by jpscaletti** [comment]
Making it optionally pre-processable by Jinja (`copier.yaml.tmpl` ?) sounds like a good idea. Loading another set of templates outside the project to do that processing not.

Like I wrote in #67, the `copier.yaml` file is the perfect place to put those "alternative sources" of templates... but they can't be used to process itself sou you would need *more*  way to specify sources... I don't like it. In that case, I really think it would be overengineering it.

**Comment by pykong** [comment]
Agreed. While I feel this feature would be great to have:
With great powers comes great chance to screw up.
Better not opening a Pandora'S box of bugs here.
