### ISSUE TITLE
Test Coverage Badge

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#75]
We may want to include a badge displaying our code coverage.
As we have fairly good coverage we should advertise this fact as another sign of good repo quality.

I have no experience with GitHub badges and hence can not recommend any service.
One that I found through googling though is [codecov.io](https://codecov.io) who provides badges like that:

![image](https://user-images.githubusercontent.com/20211140/65385956-807a1380-dd35-11e9-858b-d79a0a49bf0e.png)

**Comment by jpscaletti** [comment]
I have used https://coveralls.io in the past for this. I'll do it.

**Comment by pykong** [comment]
Great.

Wow, I didn't realize we actually have 96% coverage!
This makes our new badge look even better. :-)
