### ISSUE TITLE
Are skip and force mutually exclusive?

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#78]
In my understanding, the `skip` and `force` options represent two mutually exclusive resolution strategies.

If so we should reflect this fact in:
- ~~the cli arg parsing (`argparse` provides ways to specify [mutual exclusivity](https://docs.python.org/3/library/argparse.html#mutual-exclusion))~~
- in the `Flags` config object (`pydantic`s validators are very easy to use)
- the docs of course

**EDIT:**
We should validate in a single place. The best place is the config submodule. It will not make a difference to the user if error messages are properly generated.

**Comment by jpscaletti** [comment]
Hummm.. yes they are. In fact,  the "Overwrite filename (y/n)" prompt is really choosing between
force (overwrite) and skip (leave the file as it is).

**Comment by pykong** [comment]
The prompt does but not the **CLI**. 
But do not bother I have a fix for this in the making... ;-)
