### ISSUE TITLE
launch merge tool to solve conflicts

### ISSUE THREAD

**Issue by yucer** [jpscaletti/copier#8]
Excellent work!

It would be good if the script has the possibility of asking the user whether it wants to solve the conflicts manually.

Currently it asks:

```
    conflict  project/docker/docker-compose.yml
  Overwrite /home/yucer/src/tests/project/docker/docker-compose.yml? (y/n) [y]
```

This would be nice:

```
    conflict  project/docker/docker-compose.yml
  Overwrite /home/yucer/src/tests/project/docker/docker-compose.yml? (y/n) [y] n
  Solve conflict /home/yucer/src/tests/project/docker/docker-compose.yml? (y/n) [y] y
```

and then launch a merge-tool.

If you don't have time, I can try to do it. Just give me a clue of where I have to look first.

**Comment by jpscaletti** [comment]
I think this is outside the scope I want the project to have.

**Comment by yucer** [comment]
Would you accept if I invest from my time to implement that ?

I was testing it for interesting stuff with docker-compose, but **conflicts** is something one should ignore.

If it warns about the conflicts, why not to show it?

**Comment by pykong** [comment]
@yucer Couldn't you just run a task subsequently to the copying process?

**Comment by yucer** [comment]
@pykong That would require to make a copy of all the generated files before.

If the tool is reporting the conflict is because it has already compared both files (the generated and the existing one), in that context both files are present. I guess it is only to call diff tool as an external process immediately before asking if overwriting or not.

But your answer is indeed a good idea.

**Comment by pykong** [comment]
I'd go with @jpscaletti here, thinking that diffing is beyond the scope of this tool, but I in understand your pain. I wouldn't go down the road of implementing running tasks at different time points relative to the copying process, i.e. before transferring the files.

One hell of a hack might be to call `copier` recursively via specifying the tasks option in the yaml file. 
I have no experience doing so, though.
